/** BSc (Computer Science) Honours — Kendrapara Autonomous College, 2018 */

export const bscDegreeMetrics = {
  rollNumber: 'BS15-044',
  registrationNumber: '1502010440010022',
  stream: 'Science',
  coreSubject: 'Computer Science',
  admissionYear: '2015',
  publishedAt: '2018-05-22',
  totalMarks: 1978,
  maxMarks: 2400,
  cgpa: 8.86,
  grade: 'A+',
  division: 'First Class Honours with Distinction',
  categoryTotals: {
    AECC: 65,
    Core: 1214,
    DSE: 351,
    GEI: 141,
    GEII: 135,
    SEC: 72,
  },
  semesters: [
    {
      name: 'First Semester',
      sgpa: 8.7,
      totalMarks: 274,
      credits: 20,
      papers: [
        { subject: 'AECC SCOMP Odia', credits: 2, maxInternal: 10, maxFinal: 40, marksInternal: 8, marksFinal: 27, total: 35, creditPoints: 16, grade: 'A' },
        { subject: 'Core CSC Paper 1', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 50, total: 65, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 1', credits: 2, maxFinal: 25, marksFinal: 24, total: 24, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 2', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 47, total: 61, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 2', credits: 2, maxFinal: 25, marksFinal: 21, total: 21, creditPoints: 18, grade: 'A+' },
        { subject: 'GE I STATS Paper 1', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 31, total: 45, creditPoints: 28, grade: 'B+' },
        { subject: 'GE I STATS PrPaper 1', credits: 2, maxFinal: 25, marksFinal: 23, total: 23, creditPoints: 20, grade: 'O' },
      ],
    },
    {
      name: 'Second Semester',
      sgpa: 8.1,
      totalMarks: 255,
      credits: 20,
      papers: [
        { subject: 'AECC SCOMP EnvStud', credits: 2, maxInternal: 10, maxFinal: 40, marksInternal: 9, marksFinal: 21, total: 30, creditPoints: 14, grade: 'B+' },
        { subject: 'Core CSC Paper 3', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 13, marksFinal: 50, total: 63, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 3', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 4', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 13, marksFinal: 43, total: 56, creditPoints: 32, grade: 'A' },
        { subject: 'Core CSC PrPaper 4', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'GE II PHY Paper 1', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 9, marksFinal: 24, total: 33, creditPoints: 20, grade: 'C' },
        { subject: 'GE II PHY PrPaper 1', credits: 2, maxFinal: 25, marksFinal: 23, total: 23, creditPoints: 20, grade: 'O' },
      ],
    },
    {
      name: 'Third Semester',
      sgpa: 7.92,
      totalMarks: 329,
      credits: 26,
      papers: [
        { subject: 'Core CSC Paper 5', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 13, marksFinal: 51, total: 64, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 5', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 6', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 13, marksFinal: 38, total: 51, creditPoints: 28, grade: 'B+' },
        { subject: 'Core CSC PrPaper 6', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 7', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 26, total: 40, creditPoints: 24, grade: 'B' },
        { subject: 'Core CSC PrPaper 7', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'GE I STATS Paper 2', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 37, total: 51, creditPoints: 28, grade: 'B+' },
        { subject: 'GE I STATS PrPaper 2', credits: 2, maxFinal: 25, marksFinal: 22, total: 22, creditPoints: 18, grade: 'A+' },
        { subject: 'SEC CSC COMENG', credits: 2, maxInternal: 10, maxFinal: 40, marksInternal: 6, marksFinal: 20, total: 26, creditPoints: 12, grade: 'B' },
      ],
    },
    {
      name: 'Fourth Semester',
      sgpa: 9.54,
      totalMarks: 401,
      credits: 26,
      papers: [
        { subject: 'Core CSC Paper 8', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 55, total: 70, creditPoints: 40, grade: 'O' },
        { subject: 'Core CSC PrPaper 8', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 9', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 53, total: 68, creditPoints: 40, grade: 'O' },
        { subject: 'Core CSC PrPaper 9', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 10', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 48, total: 63, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 10', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'GE II PHY Paper 2', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 41, total: 55, creditPoints: 32, grade: 'A' },
        { subject: 'GE II PHY PrPaper 2', credits: 2, maxFinal: 25, marksFinal: 24, total: 24, creditPoints: 20, grade: 'O' },
        { subject: 'SEC CSC Paper 2', credits: 2, maxInternal: 10, maxFinal: 40, marksInternal: 10, marksFinal: 36, total: 46, creditPoints: 20, grade: 'O' },
      ],
    },
    {
      name: 'Fifth Semester',
      sgpa: 9.33,
      totalMarks: 347,
      credits: 24,
      papers: [
        { subject: 'Core CSC Paper 11', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 11, marksFinal: 58, total: 69, creditPoints: 40, grade: 'O' },
        { subject: 'Core CSC PrPaper 11', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 12', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 14, marksFinal: 51, total: 65, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 12', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'DSE CSC Paper 1', credits: 6, maxInternal: 20, maxFinal: 80, marksInternal: 20, marksFinal: 73, total: 93, creditPoints: 60, grade: 'O' },
        { subject: 'DSE CSC Paper 2', credits: 6, maxInternal: 20, maxFinal: 80, marksInternal: 20, marksFinal: 50, total: 70, creditPoints: 48, grade: 'A' },
      ],
    },
    {
      name: 'Sixth Semester',
      sgpa: 9.42,
      totalMarks: 372,
      credits: 24,
      papers: [
        { subject: 'Core CSC Paper 13', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 52, total: 67, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 13', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'Core CSC Paper 14', credits: 4, maxInternal: 15, maxFinal: 60, marksInternal: 15, marksFinal: 52, total: 67, creditPoints: 36, grade: 'A+' },
        { subject: 'Core CSC PrPaper 14', credits: 2, maxFinal: 25, marksFinal: 25, total: 25, creditPoints: 20, grade: 'O' },
        { subject: 'DSE CSC Paper 3', credits: 6, maxInternal: 20, maxFinal: 80, marksInternal: 19, marksFinal: 70, total: 89, creditPoints: 54, grade: 'A+' },
        { subject: 'DSE CSC Project', credits: 6, maxFinal: 100, marksFinal: 99, total: 99, creditPoints: 60, grade: 'O' },
      ],
    },
  ],
}
