import { bscDegreeMetrics } from './bsc-degree-semesters.js'

export const educationSeedRows = [
  {
    institution: 'Utkal University',
    degree: 'MSc (Computer Science)',
    startDate: '2018-08',
    endDate: '2020-10',
    description: 'Postgraduate degree in computer science.',
    qualificationType: 'postgraduate',
    boardOrIssuer: 'Utkal University',
    resultSummary: 'Completed MSc in Computer Science.',
    certificateUrl: null,
    subjectsJson: '[]',
    metricsJson: '{}',
    sortOrder: 1,
  },
  {
    institution: 'Kendrapara Autonomous College (Utkal University)',
    degree: 'BSc (Computer Science) Honours',
    startDate: '2015',
    endDate: '2018',
    description:
      'Three Year Degree Examination — 2018. Roll BS15-044 · Reg. 1502010440010022 · Published 22 May 2018.',
    qualificationType: 'undergraduate',
    boardOrIssuer: 'Utkal University',
    resultSummary: 'First Class Honours with Distinction · CGPA 8.86 (Grade A+)',
    certificateUrl: '/certificates/bsc-marksheet-2018.png',
    subjectsJson: JSON.stringify(
      Object.entries(bscDegreeMetrics.categoryTotals).map(([name, marks]) => ({
        name: `${name} (category total)`,
        marks,
      })),
    ),
    metricsJson: JSON.stringify(bscDegreeMetrics),
    sortOrder: 2,
  },
  {
    institution: 'Masai School',
    degree: 'Full Stack Web Development Program',
    startDate: '2022',
    endDate: '2022-10',
    description:
      'Intensive industry-aligned program covering full-stack web development and engineering practices.',
    qualificationType: 'professional',
    boardOrIssuer: 'Masai School',
    resultSummary: 'Certificate of Completion · Oct 2022 · Outstanding result and conduct',
    certificateUrl: '/certificates/masai-fullstack-2022.png',
    subjectsJson: '[]',
    metricsJson: JSON.stringify({
      certificateId: 'MASAI-FW16-299',
      learningHours: 2160,
    }),
    sortOrder: 3,
  },
  {
    institution: 'Alfa Best College of Science & Technology',
    degree: 'Higher Secondary (Science)',
    startDate: '2013',
    endDate: '2015',
    description: 'CHSE Odisha — Science stream (Regular).',
    qualificationType: 'intermediate',
    boardOrIssuer: 'Council of Higher Secondary Education, Odisha',
    resultSummary: 'Passed · First Division · Aggregate 408 marks',
    certificateUrl: '/certificates/higher-secondary-2015.png',
    subjectsJson: JSON.stringify([
      { code: 'ENG', name: 'English', maxMarks: 100, marks: 50 },
      { code: 'ODI', name: 'MIL Odia', maxMarks: 100, marks: 80 },
      { code: 'PHY', name: 'Physics', maxMarks: 70, marks: 42 },
      { code: 'PHYP', name: 'Physics (Practical)', maxMarks: 30, marks: 28 },
      { code: 'CHE', name: 'Chemistry', maxMarks: 70, marks: 50 },
      { code: 'CHEP', name: 'Chemistry (Practical)', maxMarks: 30, marks: 28 },
      { code: 'MTH', name: 'Mathematics', maxMarks: 100, marks: 39 },
      { code: 'IT', name: 'Information Technology', maxMarks: 70, marks: 62 },
      { code: 'ITP', name: 'Information Technology (Practical)', maxMarks: 30, marks: 29 },
      { name: 'Environmental Education', grade: 'A' },
      { name: 'Yoga', grade: 'A' },
      { name: 'Basic Computer Education', grade: 'A' },
    ]),
    metricsJson: JSON.stringify({
      totalMarks: 408,
      division: 'First Division',
    }),
    sortOrder: 4,
  },
  {
    institution: 'Jhadeswarpur High School, Jhadeswarpur',
    degree: 'Matriculation (Class X)',
    startDate: '2012',
    endDate: '2013',
    description: 'BSE Odisha High School Certificate Examination (Regular), February 2013.',
    qualificationType: 'matric',
    boardOrIssuer: 'Board of Secondary Education, Odisha',
    resultSummary: 'First Division · Total 406 / 600',
    certificateUrl: '/certificates/matriculation-2013.png',
    subjectsJson: JSON.stringify([
      { code: 'FLO', name: 'First Language', maxMarks: 100, marks: 48 },
      { code: 'SLE', name: 'Second Language', maxMarks: 100, marks: 70 },
      { code: 'TLS', name: 'Third Language', maxMarks: 100, marks: 87 },
      { code: 'MTH', name: 'Mathematics', maxMarks: 100, marks: 59 },
      { code: 'SCP', name: 'Physical Science', maxMarks: 50, marks: 32 },
      { code: 'SCL', name: 'Life Science', maxMarks: 50, marks: 31 },
      { code: 'SSG', name: 'Geography & Economics', maxMarks: 50, marks: 32 },
      { code: 'SSH', name: 'History & Civics', maxMarks: 50, marks: 47 },
      { name: 'Work Education', grade: 'A' },
      { name: 'Art Education', grade: 'A' },
      { name: 'Health & Physical Education', grade: 'A' },
    ]),
    metricsJson: JSON.stringify({
      totalMarks: 406,
      maxMarks: 600,
      division: 'First Division',
    }),
    sortOrder: 5,
  },
]
